# Generated by Django 6.1.1 on 2026-09-26 22:49

import django.db.models.deletion
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nomina', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Número de nómina')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre completo')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'TBL_Usuario',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=5)),
                ('tamano_mb', models.DecimalField(decimal_places=2, max_digits=4)),
                ('archivo', models.FileField(upload_to='videos/', validators=[videos.models.validar_archivo_video])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'TBL_Video',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='VideoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(db_column='nomina_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='videos_relacionados', to='videos.persona')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_relacionados', to='videos.video')),
            ],
            options={
                'db_table': 'TBL_Usuario_Video',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'video'), name='usuario_video_unico')],
            },
        ),
    ]
